# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8b6071ac-b89e-4ed9-aba2-e90cbdfd3fa4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8b6071ac-b89e-4ed9-aba2-e90cbdfd3fa4".device = "/dev/disk/by-uuid/8b6071ac-b89e-4ed9-aba2-e90cbdfd3fa4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D8E7-FC8B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
